import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import Header from "./components/Header";
import WhatsAppButton from "./components/WhatsAppButton";
import "./globals.css";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
  keywords: "Vandan,test", 
  icons: {
    icon: "./logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body
        className="bg-[#0f172a] text-white"
      >
        <Header/>
        {children}
        <Toaster position="top-right" />
        <WhatsAppButton />
        <Footer/>
      </body>
    </html>
  );
}
